// <auto-generated />
using System;
using EcoPontos.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EcoPontos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoPontos.Domain.Reward.Reward", b =>
                {
                    b.Property<int>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RewardId"));

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NecessaryPoints")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("RewardId");

                    b.ToTable("TB_Reward_GS", (string)null);
                });

            modelBuilder.Entity("EcoPontos.Domain.TaskWork.TaskWork", b =>
                {
                    b.Property<int>("TaskWorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskWorkId"));

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Type")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("TaskWorkId");

                    b.ToTable("TB_TaskWork_GS", (string)null);
                });

            modelBuilder.Entity("EcoPontos.Domain.Task_Register.TaskRegister", b =>
                {
                    b.Property<int>("RegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisterId"));

                    b.Property<int>("Duration")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PointsTotal")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("TaskDateCompleted")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("TaskWorkId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("RegisterId");

                    b.HasIndex("TaskWorkId");

                    b.HasIndex("UserId");

                    b.ToTable("TB_TaskRegister_GS", (string)null);
                });

            modelBuilder.Entity("EcoPontos.Domain.User.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("Points")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("UserId");

                    b.ToTable("TB_User_GS", (string)null);
                });

            modelBuilder.Entity("EcoPontos.Domain.Task_Register.TaskRegister", b =>
                {
                    b.HasOne("EcoPontos.Domain.TaskWork.TaskWork", "Task")
                        .WithMany()
                        .HasForeignKey("TaskWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoPontos.Domain.User.User", "User")
                        .WithMany("TaskRegisters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoPontos.Domain.User.User", b =>
                {
                    b.Navigation("TaskRegisters");
                });
#pragma warning restore 612, 618
        }
    }
}
